# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-05 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accountnumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=16, verbose_name='account number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='birth date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
