# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-05 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191006_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.TextField(default='Seoul', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='reliability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
