# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-05 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191006_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reliability',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
